version: '3.8'

services:
  bankcards-db:
    image: postgres:15
    container_name: bankcards-db
    restart: always
    environment:
      POSTGRES_DB: bankcardsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bankcards-net

  bankcards-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bankcards-app
    restart: always
    depends_on:
      - bankcards-db
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8081:8081"
    networks:
      - bankcards-net

volumes:
  postgres_data:

networks:
  bankcards-net:
    driver: bridge
