server:
  port: 8081

spring:
  profiles:
    active: dev  # активируем dev-профиль

jwt:
  secret: verySecretKeyExample1234567890verySecretKeyExample1234567890verySecretKeyExample1234567890
  access-token-expiration-ms: 3600000     # 1 час
  refresh-token-expiration-ms: 604800000  # 7 дней

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
