spring:
  datasource:
#    при использовании на локальном хосте поменяйте //bankcards-db на localhost
    url: jdbc:postgresql://bankcards-db:5432/bankcardsdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
